### ISSUE TITLE
Exception while deserializing a plugin event

### ISSUE THREAD

**Issue by amessara-billettiqueservices** [eclipse-keyple/keyple-service-java-lib#69]
Hello team,

I have an exception when receiving a plugin event from a remote plugin.

```shell
uncaughtException: java.lang.IllegalArgumentException: JSON data of the plugin event is malformed : Interfaces can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Interface name: org.eclipse.keyple.core.service.PluginEvent
	at org.eclipse.keyple.core.service.ObservableRemotePluginAdapter.onPluginEvent(ObservableRemotePluginAdapter.java:318)
```

My understanding is that the issue, comes from this 
https://github.com/eclipse-keyple/keyple-service-java-lib/blob/78d54e7171f7db7cf218b848f1a32283511d788e/src/main/java/org/eclipse/keyple/core/service/ObservableRemotePluginAdapter.java#L309-L313

`PluginEventAdapter.class` should be used instead of the interface.

I'm using the release `2.3.1` but as you can see in the linked code, it seems to be the same with `3.x`

Regards

**Comment by andrei-cristea** [comment]
Hi Aghilas,

Thank you for raising this issue.

The fix is now available in the following versions:
- `org.eclipse.keyple:keyple-service-java-lib:3.2.2`
- `org.eclipse.keyple:keyple-service-java-lib:2.3.4`

You can upgrade from version `2.3.1` to `2.3.4` without any problem.

Regards
