### ISSUE TITLE
Exception while deserializing a reader event

### ISSUE THREAD

**Issue by amessara-billettiqueservices** [eclipse-keyple/keyple-service-java-lib#70]
Hello team,

I have an exception when receiving a reader event from a remote reader.

```shell
uncaughtException: java.lang.IllegalArgumentException: JSON data of the reader event is malformed : Interfaces can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Interface name: org.calypsonet.terminal.reader.selection.ScheduledCardSelectionsResponse
  at org.eclipse.keyple.core.service.RemotePluginAdapter.onReaderEvent(RemotePluginAdapter.java:161)
```
The event looks like this

```JSON
{"readerEvent":{"pluginName":"M1SPlugin","readerName":"34:81:F4:AA:9C:A1","type":"CARD_INSERTED","scheduledCardSelectionsResponse":{"cardSelectionResponses":[{"hasMatched":true,"powerOnData":"","selectApplicationResponse":{"apdu":"6f228408315449432e494341a516bf0c13c708000000007f09285f53070c3e23061501019000","statusWord":"9000"},"cardResponse":{"apduResponses":[]}}]}}}

```
May be when initializing the GsonBuilder, the adapter to this interface should be registered?

Regards
Aghilas MESSARA

**Comment by andrei-cristea** [comment]
Hi Aghilas,

We've made the fix but are experiencing an infra issue deploying the component on sonatype.
We'll let you know as soon as it's resolved.

Regards

**Comment by amessara-billettiqueservices** [comment]
So quick!! 🙏 
I haven't mentioned it in my original post, but can you please also report it on the 2.X branch. Thank you.

**Comment by andrei-cristea** [comment]
It was planned :) Unfortunately, the infra is still out of service at the moment... I can provide the jar if you need it urgently. Regards

**Comment by amessara-billettiqueservices** [comment]
Thank you very much Andrei. I can build it locally and work with that.

**Comment by andrei-cristea** [comment]
Hi Aghilas,

The fix is now available in the following versions:

- `org.eclipse.keyple:keyple-service-java-lib:3.2.3`
- `org.eclipse.keyple:keyple-service-java-lib:2.3.5`

Regards
