### ISSUE TITLE
DistributedLocalServiceAdapter findReader(with regex ) in distributed mode cannot find pcsc reader

### ISSUE THREAD

**Issue by angelsephirot** [eclipse-keyple/keyple-service-java-lib#74]
In this mode , 
 the name of the reader cannot be managed and  iti si often somtehing that cannot be used in regex.
example: HID Global OMNIKEY 3x21 Smart Card Reader [OMNIKEY 3x21 Smart Card Reader] 00 00

private final class LocalReaderExecutor {

    private final AbstractReaderAdapter reader;
    private final JsonObject input;
    private final JsonObject output;
    private final int inputCoreApiLevel;

    /**
     * Constructor.
     *
     * @param jsonData The JSON service input data.
     * @param readerName The name of the target reader.
     */
    private LocalReaderExecutor(String jsonData, String readerName) {

      reader = (AbstractReaderAdapter) SmartCardServiceProvider.getService().findReader(readerName);
      if (reader == null) {
        throw new IllegalStateException(String.format(READER_NOT_FOUND_TEMPLATE, readerName));

**Comment by andrei-cristea** [comment]
Hi, thanks for your analysis, we'll fixed this issue quickly. Regards

**Comment by andrei-cristea** [comment]
Fixed in release [3.3.1](https://github.com/eclipse-keyple/keyple-service-java-lib/releases/tag/3.3.1)

**Comment by r34789000** [comment]
I have a problem with incorrect identification
Omnikey HID 3121 ID 076b:3031
It should be Omnikey HID 3121 ID 076b:3121
Can you help in which file the information about
registration for editing in Ubuntu server 16.04 is written
